name: Coverage

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/coverage.yml'
      - '**.rs'
      - 'Cargo.toml'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/coverage.yml'
      - '**.rs'
      - 'Cargo.toml'

jobs:
  coverage:
    name: Create coverage statistics
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v1

    - run: cargo build
    - run: cargo install cargo-tarpaulin
    - run: cargo tarpaulin --run-types Tests,Doctests --out Xml

    - uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cobertura.xml
        fail_ci_if_error: true
