name: Tests

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'
      - '**.rs'
      - 'Cargo.toml'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'
      - '**.rs'
      - 'Cargo.toml'

jobs:
  test:
    name: Tests on ${{ matrix.os }} for ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, nightly]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
